apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-review-frontend
  namespace: book-review
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-review-frontend
  template:
    metadata:
      labels:
        app: book-review-frontend
    spec:
      containers:
        - name: frontend
          image: REPLACE_FRONTEND_IMAGE  # will be overridden by kubectl set image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "/" # or external URL if backend LB exposed
