apiVersion: v1
kind: Service
metadata:
  name: book-review-frontend
  namespace: book-review
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: ClusterIP
  selector:
    app: book-review-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
