apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: book-review-ingress
  namespace: book-review
  annotations:
    kubernetes.io/ingress.class: alb

    # Internet-facing ALB
    alb.ingress.kubernetes.io/scheme: internet-facing

    # Use IP mode (required for EKS)
    alb.ingress.kubernetes.io/target-type: ip

    # Health check
    alb.ingress.kubernetes.io/healthcheck-path: /

    # Listener ports
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'

    # Optional but recommended
    alb.ingress.kubernetes.io/load-balancer-attributes: routing.http2.enabled=true

spec:
  rules:
    - http:
        paths:
          # Backend API
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: book-review-backend
                port:
                  number: 3001

          # Frontend (React / Next.js)
          - path: /
            pathType: Prefix
            backend:
              service:
                name: book-review-frontend
                port:
                  number: 80
